import { SaleType, SaleStatus, PaymentMethod } from "@prisma/client";
import type { SaleDetails } from "@/lib/sales/service";

const BASE_DATE = new Date("2026-09-25T17:30:00.000Z");

export interface ReceiptSampleScenario {
  id: string;
  label: string;
  description: string;
  data: SaleDetails;
}

export const RECEIPT_SAMPLE_SCENARIOS: ReceiptSampleScenario[] = [
  {
    id: "cash-standard",
    label: "1. Cash Walk-in (Standard)",
    description: "Walk-in cash counter sale, 2 items, paid in full, exact match.",
    data: {
      id: "mock-sale-1",
      invoiceNumber: "INV-20260925-1001",
      customerId: null,
      customer: null,
      saleType: SaleType.RETAIL,
      status: SaleStatus.COMPLETED,
      subtotal: 16500,
      discount: 0,
      totalAmount: 16500,
      paidAmount: 16500,
      creditAmount: 0,
      soldAt: BASE_DATE,
      cancellationReason: null,
      cancelledAt: null,
      createdByName: "Hanzla (Cashier)",
      updatedByName: null,
      items: [
        {
          id: "item-1",
          productId: "prod-1",
          productName: "Pepsi 1.5L PET",
          productBrand: "Pepsi",
          quantity: 10,
          unitPrice: 1200,
          totalAmount: 12000,
        },
        {
          id: "item-2",
          productId: "prod-2",
          productName: "7Up Free 500ml",
          productBrand: "7Up",
          quantity: 5,
          unitPrice: 900,
          totalAmount: 4500,
        },
      ],
      payments: [
        {
          id: "pay-1",
          amount: 16500,
          paymentMethod: PaymentMethod.CASH,
          referenceNumber: "INV-20260925-1001",
          paidAt: BASE_DATE,
          receivedByName: "Hanzla",
        },
      ],
      auditLogs: [],
    },
  },
  {
    id: "credit-sale",
    label: "2. Credit Sale (Wholesale)",
    description: "Registered B2B client, partial payment, outstanding credit, customer ledger balance.",
    data: {
      id: "mock-sale-2",
      invoiceNumber: "INV-20260925-1002",
      customerId: "cust-1",
      customer: {
        id: "cust-1",
        name: "ABC Store (Gulberg)",
        phone: "0300-1234567",
        address: "Shop 14, Main Market, Gulberg III, Lahore",
        creditAllowed: true,
        outstandingBalance: 35000,
      },
      saleType: SaleType.WHOLESALE,
      status: SaleStatus.COMPLETED,
      subtotal: 16500,
      discount: 0,
      totalAmount: 16500,
      paidAmount: 10000,
      creditAmount: 6500,
      soldAt: BASE_DATE,
      cancellationReason: null,
      cancelledAt: null,
      createdByName: "Hanzla",
      updatedByName: null,
      items: [
        {
          id: "item-1",
          productId: "prod-1",
          productName: "Pepsi 250ml Regular Glass",
          productBrand: "Pepsi",
          quantity: 10,
          unitPrice: 1200,
          totalAmount: 12000,
        },
        {
          id: "item-2",
          productId: "prod-2",
          productName: "7Up Free 250ml Glass",
          productBrand: "7Up",
          quantity: 5,
          unitPrice: 900,
          totalAmount: 4500,
        },
      ],
      payments: [
        {
          id: "pay-1",
          amount: 10000,
          paymentMethod: PaymentMethod.CASH,
          referenceNumber: "Cash Part",
          paidAt: BASE_DATE,
          receivedByName: "Hanzla",
        },
      ],
      auditLogs: [],
    },
  },
  {
    id: "containers",
    label: "3. Container Returns Tracking",
    description: "Sale with returnable glass empties and plastic crates tracked in the container ledger.",
    data: {
      id: "mock-sale-7",
      invoiceNumber: "INV-20260925-1007",
      customerId: "cust-5",
      customer: {
        id: "cust-5",
        name: "Bismillah Bakers & Sweets",
        phone: "0302-5551234",
        address: "Chungi Amar Sidhu, Ferozepur Road, Lahore",
        creditAllowed: false,
        outstandingBalance: 0,
      },
      saleType: SaleType.RETAIL,
      status: SaleStatus.COMPLETED,
      subtotal: 28800,
      discount: 0,
      totalAmount: 28800,
      paidAmount: 28800,
      creditAmount: 0,
      soldAt: BASE_DATE,
      cancellationReason: null,
      cancelledAt: null,
      createdByName: "Hanzla",
      updatedByName: null,
      items: [
        {
          id: "item-1",
          productId: "prod-1",
          productName: "Pepsi 250ml Glass Bottle (24b/Crate)",
          productBrand: "Pepsi",
          quantity: 15,
          unitPrice: 1200,
          totalAmount: 18000,
        },
        {
          id: "item-2",
          productId: "prod-2",
          productName: "7Up 250ml Glass Bottle (24b/Crate)",
          productBrand: "7Up",
          quantity: 9,
          unitPrice: 1200,
          totalAmount: 10800,
        },
      ],
      payments: [
        {
          id: "pay-1",
          amount: 28800,
          paymentMethod: PaymentMethod.CASH,
          referenceNumber: "Cash Full",
          paidAt: BASE_DATE,
          receivedByName: "Hanzla",
        },
      ],
      auditLogs: [],
      containers: {
        plasticCrates: 24,
        glassBottles: 576,
      },
    },
  },
  {
    id: "discounted",
    label: "4. Discounted Sale",
    description: "Sale with promotional discount showing subtotal, discount reduction, and net total.",
    data: {
      id: "mock-sale-3",
      invoiceNumber: "INV-20260925-1003",
      customerId: null,
      customer: null,
      saleType: SaleType.RETAIL,
      status: SaleStatus.COMPLETED,
      subtotal: 21800,
      discount: 800,
      totalAmount: 21000,
      paidAmount: 21000,
      creditAmount: 0,
      soldAt: BASE_DATE,
      cancellationReason: null,
      cancelledAt: null,
      createdByName: "Hanzla",
      updatedByName: null,
      items: [
        {
          id: "item-1",
          productId: "prod-1",
          productName: "Pepsi 1.5L PET",
          productBrand: "Pepsi",
          quantity: 10,
          unitPrice: 1450,
          totalAmount: 14500,
        },
        {
          id: "item-2",
          productId: "prod-2",
          productName: "Aquafina 500ml (Pack)",
          productBrand: "Aquafina",
          quantity: 12,
          unitPrice: 608.33,
          totalAmount: 7300,
        },
      ],
      payments: [
        {
          id: "pay-1",
          amount: 21000,
          paymentMethod: PaymentMethod.EASYPAISA,
          referenceNumber: "EP-987654321",
          paidAt: BASE_DATE,
          receivedByName: "Hanzla",
        },
      ],
      auditLogs: [],
    },
  },
  {
    id: "cancelled",
    label: "5. Cancelled Invoice",
    description: "Receipt with cancellation banner watermark and audit reason.",
    data: {
      id: "mock-sale-8",
      invoiceNumber: "INV-20260925-1008",
      customerId: null,
      customer: null,
      saleType: SaleType.RETAIL,
      status: SaleStatus.CANCELLED,
      subtotal: 12000,
      discount: 0,
      totalAmount: 12000,
      paidAmount: 12000,
      creditAmount: 0,
      soldAt: BASE_DATE,
      cancellationReason: "Customer changed mind before loading; full refund issued.",
      cancelledAt: new Date("2026-09-25T17:45:00.000Z"),
      createdByName: "Hanzla",
      updatedByName: "Hanzla",
      items: [
        {
          id: "item-1",
          productId: "prod-1",
          productName: "Pepsi 1.5L PET",
          productBrand: "Pepsi",
          quantity: 10,
          unitPrice: 1200,
          totalAmount: 12000,
        },
      ],
      payments: [
        {
          id: "pay-1",
          amount: 12000,
          paymentMethod: PaymentMethod.CASH,
          referenceNumber: "Refunded",
          paidAt: BASE_DATE,
          receivedByName: "Hanzla",
        },
      ],
      auditLogs: [],
    },
  },
];
