-- AlterTable
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "lastOperationId" UUID;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "lastUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
